apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: urial-nodejs 
  janus-idp.io/tekton: urial-nodejs
  backstage.io/kubernetes-id: urial-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: urial-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  